### ISSUE TITLE
Scala 3.3 docs.dispatcher.DispatcherDocSpec java.lang.IllegalArgumentException: no matching constructor found on

### ISSUE THREAD

**Issue by He-Pin** [apache/pekko#1081]
```scala
[01-30 07:45:26.559] [info] - using Identify *** FAILED *** (0 milliseconds)
[01-30 07:45:26.559] [info]   java.lang.IllegalArgumentException: no matching constructor found on class docs.actor.ActorDocSpec$$anon$32$Follower for arguments [class docs.actor.ActorDocSpec$$anon$32]
[01-30 07:45:26.559] [info]   at org.apache.pekko.util.Reflect$.error$1(Reflect.scala:98)
[01-30 07:45:26.559] [info]   at org.apache.pekko.util.Reflect$.findConstructor(Reflect.scala:122)
[01-30 07:45:26.559] [info]   at org.apache.pekko.actor.ArgsReflectConstructor.<init>(IndirectActorProducer.scala:109)
[01-30 07:45:26.559] [info]   at org.apache.pekko.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:74)
[01-30 07:45:26.559] [info]   at org.apache.pekko.actor.Props.producer(Props.scala:141)
[01-30 07:45:26.560] [info]   at org.apache.pekko.actor.Props.<init>(Props.scala:154)
[01-30 07:45:26.560] [info]   at org.apache.pekko.actor.Props$.apply(Props.scala:123)
```

refs: https://github.com/apache/incubator-pekko/actions/runs/7707379313/job/21004465786#step:7:35225

**Comment by pjfanning** [comment]
This also affects the 1.0.x branch - i.e this is not a new issue

**Comment by pjfanning** [comment]
Can we leave this open until we fix 1.0.x branch. But we should wait a day or 2 before merging to 1.0.x. The issue is this code is not properly tested in PR builds - so we need the nightly build to run to test this.

**Comment by He-Pin** [comment]
I tested with manually trigger, it works , but genjavadoc does not work on scala 3.

OK, let's leave it open before backported to 1.0.x

**Comment by pjfanning** [comment]
looks like the main branch nightly build is better so we should backport this change to 1.0.x

**Comment by He-Pin** [comment]
### Analysis Summary

This issue has been **fully resolved** on all supported branches.

**Root Cause**: Scala 3 compiler generates different constructor signatures for Actor classes nested inside test spec classes — the enclosing instance reference is passed as an implicit constructor parameter. `Props.apply` uses reflective constructor lookup (`Reflect.findConstructor`) which couldn't match these inner-class constructors with the arguments provided.

**Fix**: PR #1220 moved `Follower`, `SchedulerDocSpec` actors, and `DispatcherDocSpec` actors from inside test spec classes to the top-level package scope, eliminating the implicit outer-class constructor parameter.

**Released versions containing the fix**:
- `1.0.x` branch: included in **v1.0.3+** (cherry-pick PR #1225, commit `cbf97def19`)
- `1.1.x` branch: included in **v1.1.0+** (commit `c818001180`)
- All subsequent release branches (1.2.x, 1.3.x, ..., main)

**Verification**: Re-ran `docs.actor.ActorDocSpec -- -z "using Identify"` on `main` with Scala 3.3.8 — **test passes** ✅

Closing as completed.
