### ISSUE TITLE
Scala 3.3 ActorDocSpec java.lang.IllegalArgumentException: no matching constructor found 

### ISSUE THREAD

**Issue by He-Pin** [apache/pekko#1082]
```scala
01-30 07:45:26.551] [info] - using watch *** FAILED *** (0 milliseconds)
[01-30 07:45:26.551] [info]   java.lang.IllegalArgumentException: no matching constructor found on class docs.actor.ActorDocSpec$$anon$29$WatchActor for arguments [class docs.actor.ActorDocSpec$$anon$29]
[01-30 07:45:26.551] [info]   at org.apache.pekko.util.Reflect$.error$1(Reflect.scala:98)
[01-30 07:45:26.551] [info]   at org.apache.pekko.util.Reflect$.findConstructor(Reflect.scala:122)
[01-30 07:45:26.551] [info]   at org.apache.pekko.actor.ArgsReflectConstructor.<init>(IndirectActorProducer.scala:109)
[01-30 07:45:26.551] [info]   at org.apache.pekko.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:74)
[01-30 07:45:26.551] [info]   at org.apache.pekko.actor.Props.producer(Props.scala:141)
[01-30 07:45:26.551] [info]   at org.apache.pekko.actor.Props.<init>(Props.scala:154)
[01-30 07:45:26.551] [info]   at org.apache.pekko.actor.Props$.apply(Props.scala:123)
[01-30 07:45:26.551] [info]   at org.apache.pekko.actor.Props$.apply(Props.scala:96)
[01-30 07:45:26.551] [info]   at docs.actor.ActorDocSpec$$anon$29.<init>(ActorDocSpec.scala:600)
[01-30 07:45:26.551] [info]   at docs.actor.ActorDocSpec.f$proxy14$1(ActorDocSpec.scala:603)
[01-30 07:45:26.551] [info]   at docs.actor.ActorDocSpec.$init$$$anonfun$14(ActorDocSpec.scala:580)
[01-30 07:45:26.551] [info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[01-30 07:45:26.551] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[01-30 07:45:26.551] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[01-30 07:45:26.551] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[01-30 07:45:26.552] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[01-30 07:45:26.552] [info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
[01-30 07:45:26.552] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[01-30 07:45:26.552] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:138)
[01-30 07:45:26.552] [info]   at org.apache.pekko.testkit.PekkoSpec.withFixture(PekkoSpec.scala:80)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1124)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$$anonfun$1(AnyWordSpecLike.scala:1128)
[01-30 07:45:26.552] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1128)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:44)
2024-01-30 07:45:26,552 ERROR org.apache.pekko.actor.OneForOneStrategy  - Kill MDC: {pekkoAddress=pekko://ActorDocSpec, pekkoUid=5742197011161865973, pekkoSource=pekko://ActorDocSpec/user/$e, sourceThread=ActorDocSpec-pekko.actor.internal-dispatcher-4, sourceActorSystem=ActorDocSpec, pekkoTimestamp=07:45:26.552UTC}
org.apache.pekko.actor.ActorKilledException: Kill
[01-30 07:45:26.552] [info]   at org.apache.pekko.testkit.PekkoSpec.runTest(PekkoSpec.scala:80)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$$anonfun$1(AnyWordSpecLike.scala:1187)
[01-30 07:45:26.552] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1$$anonfun$1(Engine.scala:413)
[01-30 07:45:26.552] [info]   at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[01-30 07:45:26.552] [info]   at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[01-30 07:45:26.552] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[01-30 07:45:26.552] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:429)
[01-30 07:45:26.552] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[01-30 07:45:26.552] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[01-30 07:45:26.552] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1187)
[01-30 07:45:26.553] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:44)
[01-30 07:45:26.553] [info]   at org.apache.pekko.testkit.PekkoSpec.runTests(PekkoSpec.scala:80)
[01-30 07:45:26.553] [info]   at org.scalatest.Suite.run(Suite.scala:1114)
[01-30 07:45:26.553] [info]   at org.scalatest.Suite.run$(Suite.scala:564)
[01-30 07:45:26.553] [info]   at org.apache.pekko.testkit.PekkoSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(PekkoSpec.scala:80)
[01-30 07:45:26.553] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run$$anonfun$1(AnyWordSpecLike.scala:1232)
[01-30 07:45:26.553] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[01-30 07:45:26.553] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1232)
[01-30 07:45:26.553] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:44)
[01-30 07:45:26.553] [info]   at org.apache.pekko.testkit.PekkoSpec.org$scalatest$BeforeAndAfterAll$$super$run(PekkoSpec.scala:80)
[01-30 07:45:26.553] [info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[01-30 07:45:26.553] [info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:217)
[01-30 07:45:26.553] [info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:135)
[01-30 07:45:26.553] [info]   at org.apache.pekko.testkit.PekkoSpec.run(PekkoSpec.scala:80)
[01-30 07:45:26.553] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[01-30 07:45:26.553] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[01-30 07:45:26.553] [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
[01-30 07:45:26.553] [info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[01-30 07:45:26.553] [info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[01-30 07:45:26.553] [info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[01-30 07:45:26.553] [info]   at java.base/java.lang.Thread.run(Thread.java:1583)
```

refs: https://github.com/apache/incubator-pekko/actions/runs/7707379313/job/21004465786#step:7:35225

**Comment by He-Pin** [comment]
This is actually an Dotty bug.

**Comment by pjfanning** [comment]
This also affects the 1.0.x branch - i.e this is not a new issue

**Comment by He-Pin** [comment]
as it's not going to be fixed in scala 3, so we should change the code then :)
refs: https://github.com/scala/scala3/pull/19803

**Comment by pjfanning** [comment]
@He-Pin any idea what a change would look like and whether it would be possible to get it into 1.1.0-M1?

**Comment by He-Pin** [comment]
@pjfanning Yes, I'm fixing it locally, I was expected Scala 3.3.3 fix this.
