### ISSUE TITLE
Nightly builds on main and 1.0.x broken (cluster tests)

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1586]
https://github.com/apache/pekko/actions

It seems likely that the recent changes to support Akka nodes in mixed Pekko/Akka clusters have broken something in our cluster code.

```
[info] *** 32 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.pekko.cluster.MixedProtocolClusterSpec
[error] 	org.apache.pekko.cluster.ClusterLogVerboseEnabledSpec
[error] 	org.apache.pekko.cluster.JoinConfigCompatCheckerRollingUpdateSpec
[error] 	org.apache.pekko.cluster.ClusterLogVerboseDefaultSpec
[error] 	org.apache.pekko.cluster.ClusterLogDefaultSpec
[error] 	org.apache.pekko.cluster.ClusterSpec
[error] 	org.apache.pekko.cluster.JoinConfigCompatCheckerSpec
```

**Comment by pjfanning** [comment]
The test failures seem to be timeouts when forming clusters.

```
[info] - must be allowed to join a cluster with a node using the pekko protocol *** FAILED *** (6 seconds, 100 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout 6 seconds expired:
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at org.apache.pekko.testkit.TestKitBase.poll$1(TestKit.scala:310)
[info]   at org.apache.pekko.testkit.TestKitBase.awaitCond(TestKit.scala:316)
[info]   at org.apache.pekko.testkit.TestKitBase.awaitCond$(TestKit.scala:299)
[info]   at org.apache.pekko.testkit.TestKit.awaitCond(TestKit.scala:982)
[info]   at org.apache.pekko.cluster.ClusterTestKit$ClusterTestUtil.formCluster(ClusterTestKit.scala:87)
[info]   at org.apache.pekko.cluster.MixedProtocolClusterSpec.$anonfun$new$2(MixedProtocolClusterSpec.scala:65)
```
