### ISSUE TITLE
Failed: StreamConvertersSpec, an implementation is missing

### ISSUE THREAD

**Issue by He-Pin** [apache/pekko#1653]
The cause is :
```scala
        override def spliterator(): util.Spliterator[Unit] = ???
```

refs: https://github.com/apache/pekko/actions/runs/12558913651/job/35013825717?pr=1650#step:7:19268

```scala
[ERROR] [12/31/2024 20:11:02.525] [StreamConvertersSpec-pekko.actor.default-dispatcher-6] [pekko://StreamConvertersSpec/system/Materializers/StreamSupervisor-0/flow-0-0-ignoreSink] Error during preStart in [org.apache.pekko.stream.impl.JavaStreamSource$$anon$1-fromJavaStream]: an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
	at org.apache.pekko.stream.scaladsl.StreamConvertersSpec$EmptyStream$1.spliterator(StreamConvertersSpec.scala:114)
	at org.apache.pekko.stream.impl.JavaStreamSource$$anon$1.preStart(JavaStreamSource.scala:39)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:317)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:631)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:740)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:789)
	at org.apache.pekko.actor.Actor.aroundPreStart(Actor.scala:558)
	at org.apache.pekko.actor.Actor.aroundPreStart$(Actor.scala:558)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:729)
	at org.apache.pekko.actor.ActorCell.create(ActorCell.scala:653)
	at org.apache.pekko.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at org.apache.pekko.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at org.apache.pekko.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:297)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:232)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:245)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by pjfanning** [comment]
looks like this was caused by https://github.com/apache/pekko/pull/1249
